services:
  stremio-translator:
    build: .
    image: stremio-translator-addon:latest
    container_name: stremio-translator
    restart: unless-stopped
    ports:
      - "3044:7000"  # porta 3044 no host -> 7000 dentro do container
    env_file:
      - .env
    volumes:
      - ./cache:/app/cache
